pipeline {
  agent any
  parameters {
    string(name: 'TARGET_JOB_NAME', defaultValue: 'jenkins-setup', description: 'Name des Jenkins-Jobs, dessen Daten extrahiert werden sollen.')
  }
  stages {
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t jenkins-builddata ./data_extraction'
      }
    }
    stage('Run Container') {
      steps {
        withCredentials([string(credentialsId: 'jenkins-api-token', variable: 'JENKINS_TOKEN')]) {
          sh 'docker run --rm -e JENKINS_TOKEN=${JENKINS_TOKEN} -e JOB_NAME=${TARGET_JOB_NAME} jenkins-builddata > ${TARGET_JOB_NAME}_build_data.csv'
        }
      }
    }
  }
  post {
    always {
      archiveArtifacts artifacts: "${env.TARGET_JOB_NAME}_build_data.csv", fingerprint: true
    }
  }
}
