pipeline {
  agent any
  parameters {
    string(
      name: 'TARGET_JOB_NAME',
      defaultValue: 'jenkins-setup',
      description: 'Name des Jenkins-Jobs, dessen Daten extrahiert werden sollen.'
    )
    string(
      name: 'FIELDS_TO_INCLUDE',
      defaultValue: 'build_number,result,duration_sec,commits_count,estimated_duration_sec,built_on,build_url,parameters,commit_authors_count,total_commit_msg_length,change_set_kind,culprits_count,culprit_ratio,executor_name,trigger_types,error_count,build_date,build_time,build_weekday,build_hour,build_month,build_year,duration_diff,duration_ratio',
      description: 'Kommagetrennte Liste der Felder, die in die CSV exportiert werden sollen (result_bin wird immer hinzugefügt).'
    )
  }
  stages {
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t jenkins-builddata ./data_extraction'
      }
    }
    stage('Run Container') {
      steps {
        withCredentials([string(credentialsId: 'jenkins-api-token', variable: 'JENKINS_TOKEN')]) {
          sh '''
            docker run --rm \
              -e JENKINS_TOKEN=${JENKINS_TOKEN} \
              -e JOB_NAME=${TARGET_JOB_NAME} \
              -e FIELDS_TO_INCLUDE="${FIELDS_TO_INCLUDE}" \
              jenkins-builddata > ${TARGET_JOB_NAME}_build_data.csv
          '''
        }
      }
    }
  }
}
