pipeline {
    agent any
    parameters {
        // Datei-Parameter: Beim "Mit Parametern bauen" erscheint ein Upload-Feld.
        file(name: 'train_data.csv', description: 'Bitte die CSV-Datei zum Training hochladen')
        // Optional: Weitere Parameter, z. B. zur Auswahl des Modells
        string(name: 'MODEL_NAME', defaultValue: 'random_forest', description: 'Modellname: random_forest, gradient_boosting, logistic_regression, xgboost')
        string(name: 'DATE_COLUMNS', defaultValue: '', description: 'Optionale, kommagetrennte Liste von Datumsspalten')
    }
    stages {
        stage('Build Docker Image') {
            steps {
                    sh 'docker build -t model-training ./training'
            }
        }
        stage('Run Training') {
            steps {
                script {
                    def dateColumnsArg = ""
                    if (params.DATE_COLUMNS?.trim()) {
                        dateColumnsArg = "--date_columns ${params.DATE_COLUMNS}"
                    }
                    sh """
                    ls -la ${env.WORKSPACE}
                    docker run --name train-model-container -v ${env.WORKSPACE}/train_data.csv:/app/train_data.csv model-training \\
                    python train_model.py \\
                    --input_csv /app/train_data.csv \\
                    --model_name ${params.MODEL_NAME} \\
                    ${dateColumnsArg}
                    """
                    sh 'docker cp train-model-container:/app/model.pkl /tmp/model.pkl'
                    sh 'docker cp /tmp/model.pkl jenkins:/var/jenkins_home/workspace/train-model/model.pkl'
                    sh 'docker rm train-model-container'
                }
            }
        }
    }
}
